services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: red_social_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=red_social
      - DB_USER=red_social_user
      - DB_PASSWORD=red_social_password
    extra_hosts:
      - "host.docker.internal:host-gateway"